import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

    const dbUser = await prisma.user.findUnique({ where: { id: user.id }, include: { tenant: true } })
    if (!dbUser) return NextResponse.json({ error: "User not found" }, { status: 404 })

    const invoice = await prisma.invoice.findFirst({
      where: { id: params.id, tenantId: dbUser.tenantId },
      include: { customer: true, lines: true, payments: true }
    })

    if (!invoice) return NextResponse.json({ error: "Invoice not found" }, { status: 404 })

    const tenantName = dbUser.tenant.name

    // Build an HTML-based PDF (simple, no external lib needed)
    const paid = invoice.payments.reduce((a, p) => a + Number(p.amount), 0)
    const balance = Number(invoice.balanceDue) - paid

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; padding: 40px; color: #111; font-size: 14px; }
  h1 { color: #2563eb; margin: 0; }
  .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
  .invoice-meta { text-align: right; }
  .badge { background: #dcfce7; color: #166534; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; }
  .badge.unpaid { background: #fef9c3; color: #854d0e; }
  table { width: 100%; border-collapse: collapse; margin: 24px 0; }
  th { background: #f1f5f9; padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
  td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }
  .totals { margin-left: auto; width: 280px; }
  .totals tr td:first-child { color: #64748b; }
  .totals tr.grand td { font-weight: bold; font-size: 16px; color: #2563eb; border-top: 2px solid #2563eb; padding-top: 8px; }
  .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <div>
      <h1>${tenantName}</h1>
      <p style="color:#64748b;margin:4px 0">Tax Invoice</p>
    </div>
    <div class="invoice-meta">
      <h2 style="margin:0;font-size:22px;">${invoice.number}</h2>
      <p style="margin:4px 0;color:#64748b;">Issue Date: ${new Date(invoice.issueDate).toLocaleDateString('en-LK')}</p>
      <p style="margin:4px 0;color:#64748b;">Due Date: ${new Date(invoice.dueDate).toLocaleDateString('en-LK')}</p>
      <span class="badge ${balance > 0 ? 'unpaid' : ''}">${balance <= 0 ? 'PAID' : invoice.status.toUpperCase()}</span>
    </div>
  </div>

  <div style="background:#f8fafc;padding:16px;border-radius:8px;margin-bottom:24px;">
    <strong>Bill To:</strong><br/>
    <span style="font-size:16px;font-weight:600;">${invoice.customer.name}</span><br/>
    ${invoice.customer.email ? `<span style="color:#64748b">${invoice.customer.email}</span><br/>` : ''}
    ${invoice.customer.phone ? `<span style="color:#64748b">${invoice.customer.phone}</span>` : ''}
  </div>

  <table>
    <thead>
      <tr>
        <th style="width:50%">Description</th>
        <th style="text-align:right">Qty</th>
        <th style="text-align:right">Unit Price</th>
        <th style="text-align:right">Tax</th>
        <th style="text-align:right">Amount</th>
      </tr>
    </thead>
    <tbody>
      ${invoice.lines.map(line => `
        <tr>
          <td>${line.description}</td>
          <td style="text-align:right">${line.quantity}</td>
          <td style="text-align:right">LKR ${Number(line.unitPrice).toLocaleString()}</td>
          <td style="text-align:right">${Number(line.taxRate)}%</td>
          <td style="text-align:right"><strong>LKR ${Number(line.subtotal).toLocaleString()}</strong></td>
        </tr>`).join('')}
    </tbody>
  </table>

  <table class="totals">
    <tr><td>Subtotal</td><td style="text-align:right">LKR ${Number(invoice.subtotal).toLocaleString()}</td></tr>
    <tr><td>Tax</td><td style="text-align:right">LKR ${Number(invoice.tax).toLocaleString()}</td></tr>
    <tr class="grand"><td>Total</td><td style="text-align:right">LKR ${Number(invoice.total).toLocaleString()}</td></tr>
    ${balance > 0 ? `<tr><td style="color:#dc2626;font-weight:600">Balance Due</td><td style="text-align:right;color:#dc2626;font-weight:600">LKR ${balance.toLocaleString()}</td></tr>` : ''}
  </table>

  <div class="footer">
    Thank you for your business! • Generated by ${tenantName} ERP System
  </div>
</body>
</html>`

    return new Response(html, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `inline; filename="${invoice.number}.html"`,
      }
    })

  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}

// PATCH to update invoice status
export async function PATCH(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

    const dbUser = await prisma.user.findUnique({ where: { id: user.id } })
    if (!dbUser) return NextResponse.json({ error: "User not found" }, { status: 404 })

    const { status } = await request.json()

    const invoice = await prisma.invoice.update({
      where: { id: params.id, tenantId: dbUser.tenantId },
      data: { status }
    })

    return NextResponse.json({ success: true, status: invoice.status })
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
